[package]
name = "spin4"
version = "0.0.2"
license = "MIT"
description = "spin4 is an esoteric programming language that uses 4D rotations for computations."
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
anyhow = "1.0"
clap = { version = "4.5.0", features = ["derive"] }
